name: Build Web Assets

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Web
        run: npx expo export -p web

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build-dist
          path: dist
