name: Build Web Assets

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: |
          npm install --legacy-peer-deps

      - name: 🏗️ Build Expo Web Static
        run: npx expo export -p web

      - name: 📤 Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-dist
          path: dist
